"""empty message

Revision ID: 2bb53e509ba4
Revises: 
Create Date: 2025-03-21 12:35:01.472632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb53e509ba4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_artist', sa.Boolean(), nullable=True),
    sa.Column('profile_photo', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artist_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=3000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profile.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('follow_artist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_profile_id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=False),
    sa.Column('artist_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('artist_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=510), nullable=False),
    sa.Column('media_url', sa.String(length=2040), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('artist_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_song')
    op.drop_table('video')
    op.drop_table('song')
    op.drop_table('photo')
    op.drop_table('follow_artist')
    op.drop_table('artist_genres')
    op.drop_table('artist_profile')
    op.drop_table('user')
    op.drop_table('genre')
    # ### end Alembic commands ###
